config/routes.rb
Skatespotsmap::Application.routes.draw do
  resources :users
  resources :spots
  resources :comments

  root 'pages#home'

  get '/about', to: 'pages#about'

  post 'sessions', to: 'sessions#create'

  delete 'sign_out', to: 'sessions#destroy'
end

app/models/city.rb
class City
  def self.find(zip)
    response = Faraday.get('http://maps.googleapis.com/maps/api/geocode/json') do |request|
      request.params['address'] = zip
    end

    new(JSON.parse(response.body))
  end

  def initialize(city_hash)
    @city_hash = city_hash
  end

  def name
    @city_hash['results'].first['formatted_address']
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :spot
  validates_presence_of :comment
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates_presence_of :city, :state, :address_1, :zip_code, :description, :filepicker_url
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :spots
  has_many :comments
  include Authem::User

  def filepicker_url
    super.presence || default_url
  end

  def default_url
    "https://www.filepicker.io/api/file/zhLWjAZvSMiF82eI7Nlr"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Authem::ControllerSupport
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @spot = Spot.find(comment_params[:spot_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to spot_path(@spot)
    else
      redirect_to spot_path(@spot)
    end
  end

  def comment_params
    params.require(:comment).permit(
      :comment,
      :user_id,
      :spot_id
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:search].present?
      @spots = Spot.fuzzy_search(params[:search]).paginate(page: params[:page], order: 'created_at DESC', per_page: 15).order(:city, :address_1)
    else
      @spots = Spot.paginate(page: params[:page], order: 'created_at DESC',  per_page: 15)
    end
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path
    else
      flash[:alert] = 'Invalid Login'
      redirect_to new_user_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
  end

  def show
    @spot = Spot.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.user = current_user
    if @spot.save
      redirect_to root_path
    else
      render new_spot_path
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    @spot.update_attributes(spot_params)
    redirect_to spot_path(@spot.id)
  end

  def destroy
    Spot.find(params[:id]).destroy
    redirect_to root_path
  end

  def spot_params
    params.require(:spot).permit(
      :city,
      :state,
      :user_id,
      :zip_code,
      :address_1,
      :address_2,
      :description,
      :filepicker_url,
      :additional_info
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def update
    current_user.update_attributes(user_params)
    redirect_to user_path(current_user)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_path
    else
      render new_user_path
    end
  end

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation,
      :filepicker_url
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
%head
  %title Skatespotsmap
  = stylesheet_link_tag    "application", media: "all"
  = javascript_include_tag "jquery", "application"
  = filepicker_js_include_tag
  = csrf_meta_tags

%body#main
  %div.links
    %h1
      = link_to 'Skate Spots Map', root_path, id: 'header_link'
    = link_to 'About Site', about_path, class: 'layout_link'
    - if signed_in?
      = link_to 'Create Spot', new_spot_path, class: 'layout_link'
    - else
      = link_to 'Sign In', new_user_path, class: 'layout_link'
  - if signed_in?
    %div.username_div
      %span.username
        = filepicker_image_tag current_user.filepicker_url
        = link_to current_user.username, user_path(current_user.id)
        - if current_user.admin?
          (admin)
      = link_to 'Sign Out', sign_out_path, method: :delete, class: 'layout_link', id: 'sign_out'
  = yield

app/views/pages/about.html.haml
%h2 About This Application

%p#about_text This is an application to view skate spots. This can be both for learning spots in your area as well as show the USA spots that you have found over the years.

%ul#about_ul
  Usage:
  %li.about_li Create and view spots around the US.
  %li.about_li Clicking 'Skate Spots Maps' (top of screen) sends you to the home page.
  When creating a spot:
  %li.about_li A spot consists of the address, description, additional info, and a picture
  %li.about_li Description and additional info are different, description is what the spot is while additional info is useful tips for skating the spot.
  %li.about_li Always make the picture a clear representation of the spot.
  %li.about_li Always make sure the address is correct.

app/views/pages/city.html.haml
%h1 Zip Codes
%h2
  = @city.name

app/views/pages/home.html.haml
= form_tag(root_path, method: :get) do
  = text_field_tag :search
  = submit_tag 'Search', class: 'search'
- if @spots.present?
  - @spots.each do |spot|
    %div.spot
      %ul
        %li
          = spot.address_1
          = spot.address_2
        %li
          = spot.city
          ,
          = spot.state
          = spot.zip_code
        %li.home_images= link_to(filepicker_image_tag(spot.filepicker_url), spot_path(spot.id))
- else
  %p#seach_error
    Sorry, no spots match your search

= will_paginate @spots

app/views/spots/city.html.haml
%h1 Cities
%h2
  - if @city.present?
    = @city.name

%div.city_spot
  %ul
    - @cities.each do |city|
      %li= link_to city, city_path(address: city.parameterize)

app/views/spots/edit.html.haml
%div#create_spot_form
  = form_for(@spot) do |f|
    %ul.left

      %li= f.label :address_1
      %li= f.text_field :address_1

      %li= f.label :address_2
      %li= f.text_field :address_2

      %li= f.label :city
      %li= f.text_field :city

      %li= f.label :state
      %li= f.text_field :state

      %li= f.label :zip_code
      %li= f.text_field :zip_code

      %li= f.submit class: 'submit', id: 'update_spot'

    %ul.right
      %li= f.label :description
      %li= f.text_area :description

      %li= f.label :additional_info, id: 'additional info'
      %li= f.text_area :additional_info

app/views/spots/new.html.haml
%div#create_spot_form
  = form_for(@spot) do |f|
    = f.hidden_field :user_id, value: current_user.id
    %ul.left

      %li= f.label :address_1
      %li= f.text_field :address_1

      %li= f.label :address_2
      %li= f.text_field :address_2

      %li= f.label :city
      %li= f.text_field :city

      %li= f.label :state
      %li= f.text_field :state

      %li= f.label :zip_code
      %li= f.text_field :zip_code

      %li= f.label :filepicker_url, 'Image of Spot'
      %li= f.filepicker_field :filepicker_url

    %ul.right
      %li= f.label :description
      %li= f.text_area :description, placeholder: 'A little bit of information on what the spot is.'

      %li= f.label :additional_info
      %li= f.text_area :additional_info
      %li= f.submit 'Create Spot', class: 'submit', id: 'create_spot'

app/views/spots/show.html.haml
%div.full_size_spot
  %div.filepicker_url= filepicker_image_tag @spot.filepicker_url
  %div.description
    %ul#desc
      %p.address
        = @spot.address_1
        = @spot.address_2
        = @spot.city
        = @spot.state
        = @spot.zip_code
      %li=label_tag :Description
      %li= @spot.description

    %ul#additional_info
      %li= label_tag :Additional_Info
      %li= @spot.additional_info
    - if current_user.present? && current_user.admin?
      %div
        = link_to 'Edit Spot', edit_spot_path(@spot.id)
        = link_to 'Delete Spot', spot_path(@spot), method: :delete, confirm: 'Are you sure?', class: 'delete'
%div.comment
  %ul.view_comment
    - if @spot.comments.present?
      - @spot.comments.each do |comment|
        %li
          %span.comment_username
            = filepicker_image_tag comment.user.filepicker_url
            = comment.user.username + ':'
          %span.comment_text
            = comment.comment
    - else
      %p No comments yet
    %div.new_comment
      = form_for(@comment) do |f|
        = f.hidden_field :spot_id, value: @spot.id
        %li#comment_label
          Comment
        - if current_user.present?
          %li= f.text_area :comment, class: 'comment_area'

          %li= f.submit :Comment , class: 'post_comment'
        - else
          Must be signed in to comment

app/views/users/edit.html.haml
%div.field_holder
  %div.sign_up_form
    %p Sign Up
    %ul
      = form_for(current_user) do |f|
        %li= f.label :username
        %li= f.text_field :username

        %li= f.label :email
        %li= f.text_field :email

        %li= f.label 'Choose an Avatar'
        %li= f.filepicker_field :filepicker_url

        %li= f.submit 'Update', class: 'submit'

app/views/users/new.html.haml
%div.field_holder
  %div.sign_up_form
    %p Sign Up
    %ul
      = form_for(@user) do |f|
        %li= f.label :username
        %li= f.text_field :username

        %li= f.label :email
        %li= f.text_field :email

        %li= f.label :password
        %li= f.password_field :password

        %li= f.label :password_confirmation
        %li= f.password_field :password_confirmation

        %li= f.label 'Choose an Avatar'
        %li= f.filepicker_field :filepicker_url

        %li= f.submit 'Sign Up', class: 'submit'

  %div.sign_in_form
    %p Sign In
    %ul
      = form_tag(sessions_path) do
        - flash.keys.each do |key|
          %p{class: key}= flash[key.to_sym]
        %li= label_tag :email
        %li= text_field_tag :email, nil

        %li= label_tag :password
        %li= password_field_tag :password, nil

        %li= submit_tag 'Sign In', class: 'submit'

app/views/users/show.html.haml
%div.user_attributes
  %p
    %ul.show_username
      %li
        username:
        = current_user.username
      %li
        email:
        = current_user.email
      %li
        = link_to 'Edit User', edit_user_path(current_user)
  %div= filepicker_image_tag current_user.filepicker_url

%div
  %p#created_spots
    Spots that you created

  - current_user.spots.each do |spot|
    %div.spot
      %ul
        %li
          = spot.address_1
          = spot.address_2
        %li
          = spot.city
          ,
          = spot.state
          = spot.zip_code
        %li.home_images= link_to(filepicker_image_tag(spot.filepicker_url), spot_path(spot.id))